In [3]:
import pandas as pd

df = pd.read_csv('all_reviews.csv')

In [4]:
df.head(20)

,source,page_url,review_id,author,date_text,rating,content
0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1685046739093413392,peppecavallari,11/02/2026,1,Deux mois passés en demandant à être remboursé...
1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1239583259843510336,aburumov,04/02/2026,1,"J'ai acheté deux meubles chez eux, pour au fin..."
2,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3771247570900608623,111324coupigny,04/02/2026,1,Service client Cdiscount complètement à la rue...
3,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-5220899007627930716,yevheniiachy,14/01/2026,1,Expérience déplorable. Suite à un achat sur Cd...
4,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-8142806620887166430,stephanerandunu,14/01/2026,1,Achat d'un DJ Furby défectueux dès le déballag...
5,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-1349306928094868084,maurelfabien7,12/01/2026,1,Site à fuir ! Aucun geste commercial pour une ...
6,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-9068169526581445088,francoisdacher,10/01/2026,5,"CDiscount, c'est le site pour les achats série..."
7,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:6059065848958261919,barlier350,09/01/2026,1,A fuir littéralement ! J'ai acheté un sèche-li...
8,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-7606551154897050886,benjaminli7mand,05/01/2026,1,Pratique commerciale trompeuse.\nJ'ai acheté d...
9,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-923180415306204734,calamarrant,05/01/2026,5,La commande s'est très bien déroulée. La livra...
10,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:4240753458989459407,isabju06,02/01/2026,5,"Site très bien fait, choix variés et prix comp..."
11,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:6219162639002739812,mickaelcroquet,30/12/2025,1,Prélèvement de 404 euros directement sur mon c...
12,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:2127724667949870602,mmartins63118,24/12/2025,5,Cdiscount est une plateforme incontournable po...
13,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:5510675875239937695,alardludovicc,20/12/2025,1,Après une première commande qui s'était correc...
14,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:8927002888496864685,helene17768,12/12/2025,1,J'ai reçu un article endommagé. Impossible de ...
15,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:4219381110327163161,vera581334,09/12/2025,1,"Avec un bon d'achats de 300€, il leur faut le ..."
16,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-8178013995038175351,mexpo0411,04/12/2025,5,Très belle expérience d'achat. Le site propose...
17,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:7241770636948986844,dimitrisechoy,24/11/2025,1,Commandé un lit pour un anniversaire avec un d...
18,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3439402453685954107,charlottenavon,17/11/2025,5,Site e-commerce français où l'on trouve de tou...
19,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-4932981823417352314,sergepoyet,14/11/2025,1,"Je commande un logiciel, celui-ci doit être en..."

In [5]:
#Création d'un modele multi-label
#classification de problèmes à partir du texte.

In [7]:
df_multilab = pd.read_csv('all_reviews_multilabel.csv')
df_multilab.head(20)

,concurrent,rating,content,problemes_detectes,nb_problemes_detectes,pb_remboursement_avoir,pb_livraison_colis_retard,pb_service_client_sav,pb_produit_defectueux_non_conforme,pb_paiement_prelevement_facturation,pb_commande_annulation_stock,pb_prix_promo_conditions,pb_site_appli_compte,source,page_url,review_id,author,date_text
0,cdiscount,1,Deux mois passés en demandant à être remboursé...,pb_remboursement_avoir; pb_service_client_sav,2,1,0,1,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1685046739093413392,peppecavallari,11/02/2026
1,cdiscount,1,"J'ai acheté deux meubles chez eux, pour au fin...",pb_produit_defectueux_non_conforme,1,0,0,0,1,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1239583259843510336,aburumov,04/02/2026
2,cdiscount,1,Service client Cdiscount complètement à la rue...,pb_service_client_sav; pb_paiement_prelevement...,3,0,0,1,0,1,0,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3771247570900608623,111324coupigny,04/02/2026
3,cdiscount,1,Expérience déplorable. Suite à un achat sur Cd...,pb_service_client_sav; pb_prix_promo_condition...,3,0,0,1,0,0,0,1,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-5220899007627930716,yevheniiachy,14/01/2026
4,cdiscount,1,Achat d'un DJ Furby défectueux dès le déballag...,pb_remboursement_avoir; pb_produit_defectueux_...,3,1,0,0,1,0,0,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-8142806620887166430,stephanerandunu,14/01/2026
5,cdiscount,1,Site à fuir ! Aucun geste commercial pour une ...,pb_commande_annulation_stock; pb_site_appli_co...,2,0,0,0,0,0,1,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-1349306928094868084,maurelfabien7,12/01/2026
6,cdiscount,5,"CDiscount, c'est le site pour les achats série...",aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-9068169526581445088,francoisdacher,10/01/2026
7,cdiscount,1,A fuir littéralement ! J'ai acheté un sèche-li...,pb_remboursement_avoir; pb_produit_defectueux_...,3,1,0,0,1,0,1,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:6059065848958261919,barlier350,09/01/2026
8,cdiscount,1,Pratique commerciale trompeuse.\nJ'ai acheté d...,pb_remboursement_avoir; pb_livraison_colis_ret...,5,1,1,0,0,1,1,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-7606551154897050886,benjaminli7mand,05/01/2026
9,cdiscount,5,La commande s'est très bien déroulée. La livra...,aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-923180415306204734,calamarrant,05/01/2026
10,cdiscount,5,"Site très bien fait, choix variés et prix comp...",aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:4240753458989459407,isabju06,02/01/2026
11,cdiscount,1,Prélèvement de 404 euros directement sur mon c...,pb_remboursement_avoir; pb_livraison_colis_ret...,6,1,1,1,1,1,0,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:6219162639002739812,mickaelcroquet,30/12/2025
12,cdiscount,5,Cdiscount est une plateforme incontournable po...,aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:2127724667949870602,mmartins63118,24/12/2025
13,cdiscount,1,Après une première commande qui s'était correc...,pb_remboursement_avoir; pb_livraison_colis_ret...,6,1,1,1,0,1,1,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:5510675875239937695,alardludovicc,20/12/2025
14,cdiscount,1,J'ai reçu un article endommagé. Impossible de ...,pb_remboursement_avoir; pb_produit_defectueux_...,2,1,0,0,1,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:8927002888496864685,helene17768,12/12/2025
15,cdiscount,1,"Avec un bon d'achats de 300€, il leur faut le ...",pb_remboursement_avoir; pb_prix_promo_conditions,2,1,0,0,0,0,0,1,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:4219381110327163161,vera581334,09/12/2025
16,cdiscount,5,Très belle expérience d'achat. Le site propose...,aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-8178013995038175351,mexpo0411,04/12/2025
17,cdiscount,1,Commandé un lit pour un anniversaire avec un d...,pb_remboursement_avoir; pb_livraison_colis_ret...,3,1,1,0,0,0,1,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:7241770636948986844,dimitrisechoy,24/11/2025
18,cdiscount,5,Site e-commerce français où l'on trouve de tou...,aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3439402453685954107,charlottenavon,17/11/2025
19,cdiscount,1,"Je commande un logiciel, celui-ci doit être en...",pb_remboursement_avoir; pb_livraison_colis_ret...,5,1,1,1,0,1,1,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-4932981823417352314,sergepoyet,14/11/2025

J’ai d’abord fait une pré-labellisation automatique par règles de mots-clés.

L’idée était simple : pour chaque famille de problème, on définit une liste de mots ou expressions associés.

Par exemple, pour le remboursement :

remboursé
remboursement
rembourser
avoir
bon d’achat

Si un avis négatif contient ces mots, on active :

pb_remboursement_avoir = 1

Pour la livraison :

livraison
colis
retard
transporteur
point relais
livreur

On active :

pb_livraison_colis_retard = 1

Pour le service client :

service client
SAV
réclamation
appel
mail
réponse
relance
contact

On active :

pb_service_client_sav = 1

Donc la méthode repose sur une logique explicable :

Si un avis négatif contient des termes associés à un problème, alors ce problème est marqué comme présent.

Pourquoi on a filtré sur les avis négatifs ?

J’ai appliqué la labellisation principalement sur les avis avec :

rating <= 2

Parce que le but était d’identifier ce qui ne va pas.

C’est important, parce qu’un avis positif peut contenir des mots comme :

livraison rapide
service client efficace
produit conforme

Si on ne filtre pas, le simple mot “livraison” pourrait déclencher un faux problème de livraison, alors que le commentaire est positif.

Donc le filtre rating <= 2 permet de se concentrer sur les avis réellement critiques.

In [9]:
df_check = df_multilab[df_multilab["rating"] <= 2].copy()


df_check.head(100)

,concurrent,rating,content,problemes_detectes,nb_problemes_detectes,pb_remboursement_avoir,pb_livraison_colis_retard,pb_service_client_sav,pb_produit_defectueux_non_conforme,pb_paiement_prelevement_facturation,pb_commande_annulation_stock,pb_prix_promo_conditions,pb_site_appli_compte,source,page_url,review_id,author,date_text
0,cdiscount,1,Deux mois passés en demandant à être remboursé...,pb_remboursement_avoir; pb_service_client_sav,2,1,0,1,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1685046739093413392,peppecavallari,11/02/2026
1,cdiscount,1,"J'ai acheté deux meubles chez eux, pour au fin...",pb_produit_defectueux_non_conforme,1,0,0,0,1,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1239583259843510336,aburumov,04/02/2026
2,cdiscount,1,Service client Cdiscount complètement à la rue...,pb_service_client_sav; pb_paiement_prelevement...,3,0,0,1,0,1,0,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3771247570900608623,111324coupigny,04/02/2026
3,cdiscount,1,Expérience déplorable. Suite à un achat sur Cd...,pb_service_client_sav; pb_prix_promo_condition...,3,0,0,1,0,0,0,1,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-5220899007627930716,yevheniiachy,14/01/2026
4,cdiscount,1,Achat d'un DJ Furby défectueux dès le déballag...,pb_remboursement_avoir; pb_produit_defectueux_...,3,1,0,0,1,0,0,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-8142806620887166430,stephanerandunu,14/01/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,cdiscount,1,L'intérêt du client ?\nNon !\nÇa ne dérange pa...,aucun_label_detecte,0,0,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-2404264461853529206,eric040401,25/07/2023
230,cdiscount,1,Bonjour ! C'est à propos de ma commande aspira...,pb_commande_annulation_stock; pb_prix_promo_co...,3,0,0,0,0,0,1,1,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3642793131032935055,danypoupee,04/07/2023
231,cdiscount,1,Le service Cdiscount à volonté est un piège po...,pb_remboursement_avoir,1,1,0,0,0,0,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:6569334678239615173,sydgemghost,03/07/2023
233,cdiscount,1,Livraison trop tardive et non respectée.\nAppe...,pb_remboursement_avoir; pb_livraison_colis_ret...,5,1,1,1,1,1,0,0,0,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:1419775153539445884,orqueadrid,28/06/2023
236,cdiscount,1,Bonjour !\nJe me trompe ou je suis le seul à v...,pb_paiement_prelevement_facturation; pb_comman...,3,0,0,0,0,1,1,0,1,poulpeo,https://www.poulpeo.com/avis/cdiscount.htm,poulpeo:-3883092147168406439,henrichicot77,27/06/2023

In [12]:
label_cols = [col for col in df.columns if col.startswith("pb_")]

cols_verif = [
    "concurrent",
    "rating",
    "content",
    "problemes_detectes",
    "nb_problemes_detectes"
] + label_cols

df_verif = df_multilab[df_multilab["rating"] <= 2][cols_verif].copy()

df_verif.to_csv("avis_negatifs_a_verifier.csv", index=False, encoding="utf-8-sig")

In [13]:
import pandas as pd

df = pd.read_csv("all_reviews_multilabel.csv", encoding="utf-8-sig")

label_cols = [col for col in df.columns if col.startswith("pb_")]

df_neg = df[df["rating"] <= 2].copy()

resume = (
    df_neg
    .groupby("concurrent")[label_cols]
    .mean()
    .mul(100)
    .round(1)
)

resume

,pb_remboursement_avoir,pb_livraison_colis_retard,pb_service_client_sav,pb_produit_defectueux_non_conforme,pb_paiement_prelevement_facturation,pb_commande_annulation_stock,pb_prix_promo_conditions,pb_site_appli_compte
concurrent,,,,,,,,
boulanger,28.2,38.0,63.4,49.3,11.3,63.4,29.6,29.6
cdiscount,36.1,37.3,50.6,39.4,20.7,43.6,34.0,39.0
conforama,25.6,44.8,48.8,44.8,18.4,48.0,26.4,35.2
darty,35.0,41.0,55.0,45.0,15.0,37.0,34.0,28.0
fnac,30.9,45.5,52.7,38.2,14.5,47.3,21.8,25.5

In [ ]:
#55,2 % des avis négatifs de ce concurrent mentionnent un problème de service client / SAV.

In [ ]:
#avoir le nombre réel d’avis par problème
resume_count = (
    df_neg
    .groupby("concurrent")[label_cols]
    .sum()
    .astype(int)
)

resume_count

,pb_remboursement_avoir,pb_livraison_colis_retard,pb_service_client_sav,pb_produit_defectueux_non_conforme,pb_paiement_prelevement_facturation,pb_commande_annulation_stock,pb_prix_promo_conditions,pb_site_appli_compte
concurrent,,,,,,,,
boulanger,20,27,45,35,8,45,21,21
cdiscount,87,90,122,95,50,105,82,94
conforama,32,56,61,56,23,60,33,44
darty,35,41,55,45,15,37,34,28
fnac,17,25,29,21,8,26,12,14

In [ ]:
#faire un tableau propre avec volume + pourcentage
nb_avis_negatifs = df_neg.groupby("concurrent").size().rename("nb_avis_negatifs")

resume_final = resume_count.copy()

for col in label_cols:
    resume_final[col + "_pct"] = resume[col]

resume_final = resume_final.join(nb_avis_negatifs)

resume_final

,pb_remboursement_avoir,pb_livraison_colis_retard,pb_service_client_sav,pb_produit_defectueux_non_conforme,pb_paiement_prelevement_facturation,pb_commande_annulation_stock,pb_prix_promo_conditions,pb_site_appli_compte,pb_remboursement_avoir_pct,pb_livraison_colis_retard_pct,pb_service_client_sav_pct,pb_produit_defectueux_non_conforme_pct,pb_paiement_prelevement_facturation_pct,pb_commande_annulation_stock_pct,pb_prix_promo_conditions_pct,pb_site_appli_compte_pct,nb_avis_negatifs
concurrent,,,,,,,,,,,,,,,,,
boulanger,20,27,45,35,8,45,21,21,28.2,38.0,63.4,49.3,11.3,63.4,29.6,29.6,71
cdiscount,87,90,122,95,50,105,82,94,36.1,37.3,50.6,39.4,20.7,43.6,34.0,39.0,241
conforama,32,56,61,56,23,60,33,44,25.6,44.8,48.8,44.8,18.4,48.0,26.4,35.2,125
darty,35,41,55,45,15,37,34,28,35.0,41.0,55.0,45.0,15.0,37.0,34.0,28.0,100
fnac,17,25,29,21,8,26,12,14,30.9,45.5,52.7,38.2,14.5,47.3,21.8,25.5,55

In [16]:
probleme_principal = resume.idxmax(axis=1)
score_principal = resume.max(axis=1)

top_probleme = pd.DataFrame({
    "probleme_principal": probleme_principal,
    "pourcentage": score_principal
})

top_probleme

               probleme_principal  pourcentage
concurrent
boulanger   pb_service_client_sav         63.4
cdiscount   pb_service_client_sav         50.6
conforama   pb_service_client_sav         48.8
darty       pb_service_client_sav         55.0
fnac        pb_service_client_sav         52.7

In [17]:
top3_par_concurrent = (
    resume
    .stack()
    .reset_index()
)

top3_par_concurrent.columns = ["concurrent", "probleme", "pourcentage"]

top3_par_concurrent = (
    top3_par_concurrent
    .sort_values(["concurrent", "pourcentage"], ascending=[True, False])
    .groupby("concurrent")
    .head(3)
)

top3_par_concurrent

   concurrent                            probleme  pourcentage
2   boulanger               pb_service_client_sav         63.4
5   boulanger        pb_commande_annulation_stock         63.4
3   boulanger  pb_produit_defectueux_non_conforme         49.3
10  cdiscount               pb_service_client_sav         50.6
13  cdiscount        pb_commande_annulation_stock         43.6
11  cdiscount  pb_produit_defectueux_non_conforme         39.4
18  conforama               pb_service_client_sav         48.8
21  conforama        pb_commande_annulation_stock         48.0
17  conforama           pb_livraison_colis_retard         44.8
26      darty               pb_service_client_sav         55.0
27      darty  pb_produit_defectueux_non_conforme         45.0
25      darty           pb_livraison_colis_retard         41.0
34       fnac               pb_service_client_sav         52.7
37       fnac        pb_commande_annulation_stock         47.3
33       fnac           pb_livraison_colis_retard         45.5

In [ ]:
#Donc le SAV devient souvent le label dominant, parce qu’il accompagne presque tous les autres problèmes.

#Chez Boulanger, les avis négatifs mentionnent très fortement le service client et les problèmes de commande, d’annulation ou de stock. Les problèmes de produit défectueux ou non conforme arrivent aussi très haut.

#Le fait que service_client_sav et commande_annulation_stock soient tous les deux à 63.4 % veut dire qu’ils sont aussi fréquents l’un que l’autre dans les avis négatifs Boulanger.

#Chez Cdiscount, les avis négatifs sont surtout liés au service client, puis aux problèmes de commande, annulation ou disponibilité, et enfin aux produits défectueux ou non conformes.

#Chez Conforama, les avis négatifs se concentrent autour du service client, des problèmes de commande ou de stock, et des problèmes de livraison.

#Chez Darty, le service client est le problème le plus fréquent dans les avis négatifs, mais les problèmes de produit défectueux ou non conforme et de livraison sont également très présents.

#Chez Fnac, les avis négatifs mentionnent surtout le service client, puis les problèmes de commande ou de stock, et enfin la livraison.

#L’analyse multi-label des avis négatifs montre que le service client / SAV constitue un irritant transversal pour 
# l’ensemble des concurrents étudiés. Ce résultat doit toutefois être interprété avec prudence, 
# car le service client est souvent mentionné après un autre problème initial : commande annulée, livraison en retard, 
# produit défectueux ou remboursement non reçu.

#Des différences apparaissent néanmoins selon les enseignes. 
#Boulanger et Cdiscount sont davantage associés aux problèmes de commande, d’annulation ou de stock, 
#ainsi qu’aux produits défectueux ou non conformes. Conforama et Fnac font ressortir un trio service client, commande et livraison. 
#Darty se distingue davantage par les problèmes de produit et de livraison.

In [ ]:
#top sans le SAV
label_cols_sans_sav = [
    col for col in label_cols 
    if col != "pb_service_client_sav"
]

resume_sans_sav = (
    df_neg
    .groupby("concurrent")[label_cols_sans_sav]
    .mean()
    .mul(100)
    .round(1)
)

probleme_principal_sans_sav = pd.DataFrame({
    "probleme_principal_sans_sav": resume_sans_sav.idxmax(axis=1),
    "pourcentage": resume_sans_sav.max(axis=1)
})

probleme_principal_sans_sav

                   probleme_principal_sans_sav  pourcentage
concurrent
boulanger         pb_commande_annulation_stock         63.4
cdiscount         pb_commande_annulation_stock         43.6
conforama         pb_commande_annulation_stock         48.0
darty       pb_produit_defectueux_non_conforme         45.0
fnac              pb_commande_annulation_stock         47.3

J’ai d’abord transformé les commentaires clients en données exploitables grâce à une approche de labellisation multi-label. L’objectif était d’identifier les différentes familles de problèmes évoquées dans les avis négatifs, comme le service client, la livraison, le remboursement, les produits défectueux ou les problèmes de commande.

J’ai choisi une approche multi-label parce qu’un même avis peut contenir plusieurs irritants. Par exemple, un client peut se plaindre à la fois d’un retard de livraison, d’un service client injoignable et d’un remboursement non reçu.

La première labellisation a été réalisée de manière automatique à partir de règles de mots-clés. Chaque catégorie de problème a été associée à des termes caractéristiques. Les labels ont ensuite été appliqués uniquement aux avis négatifs, c’est-à-dire aux avis ayant une note inférieure ou égale à 2, afin de limiter les faux positifs.

Cette méthode a été retenue car elle est explicable, contrôlable et adaptée à une première analyse concurrentielle. Elle permet de comparer les enseignes sur les problèmes les plus fréquemment mentionnés, tout en gardant la possibilité de vérifier et corriger les labels manuellement avant un éventuel entraînement de modèle de machine learning.

In [ ]:
#Une fois les labels vérifiés, on pourrait entraîner un modèle pour apprendre à reconnaître automatiquement les problèmes dans de nouveaux avis.

#Mais pour ton analyse actuelle, tu peux déjà exploiter les labels pour faire :

#top 3 des problèmes par concurrent
#problème principal sans le SAV
#problèmes surreprésentés par rapport à la moyenne
#comparaison entre concurrents